let page="home",selected="all",alertState="active";const $=s=>document.querySelector(s);
const tel=v=>"tel:"+String(v).replace(/[^\d+]/g,""),sms=v=>"sms:"+String(v).replace(/[^\d+]/g,""),wa=v=>"https://wa.me/"+String(v).replace(/\D/g,"");
function categoryStrip(){let s=$("#categoryStrip");s.innerHTML='<button class="cat active" data-cat="all">All</button>'+ALERT_CATEGORIES.map(c=>`<button class="cat" data-cat="${c.id}">${c.name}</button>`).join("");s.querySelectorAll(".cat").forEach(b=>b.onclick=()=>{selected=b.dataset.cat;s.querySelectorAll(".cat").forEach(x=>x.classList.toggle("active",x===b));renderAlerts()})}
function alertCard(a,inactive=false){return `<article class="card ${inactive?"inactive":""}"><div class="card-title">${a.title}</div><div class="meta"><span class="badge">${a.category}</span>${a.detail}</div></article>`}
function renderAlerts(){let l=selected==="all"?ALERTS:ALERTS.filter(a=>a.category===selected);let rows=l.filter(a=>a.status===alertState);$("#content").innerHTML=`<div class="subtabs">${["active","expired","inactive"].map(x=>`<button class="subtab ${x===alertState?"active":""}" data-state="${x}">${x[0].toUpperCase()+x.slice(1)}</button>`).join("")}</div><h2>${alertState[0].toUpperCase()+alertState.slice(1)} Alerts</h2><div class="stack">${rows.map(a=>alertCard(a,alertState!=="active")).join("")||'<div class="empty">No '+alertState+' alerts</div>'}</div>`;$("#content").querySelectorAll(".subtab").forEach(b=>b.onclick=()=>{alertState=b.dataset.state;renderAlerts()})}
function deviceContacts(){try{return JSON.parse(localStorage.getItem("local-alerts-contacts")||"[]")}catch{return[]}}
function contactCard(c){let b=[];if(c.phone)b.push(`<a class="action" href="${tel(c.phone)}">☎ Call</a>`);if(c.sms)b.push(`<a class="action" href="${sms(c.sms)}">✉ SMS</a>`);if(c.whatsapp)b.push(`<a class="action" target="_blank" rel="noopener" href="${wa(c.whatsapp)}">💬 WhatsApp</a>`);if(c.email)b.push(`<a class="action" href="mailto:${c.email}">✉ Email</a>`);if(c.website)b.push(`<a class="action" target="_blank" rel="noopener" href="${c.website}">🌐 Website</a>`);return `<article class="card"><div class="card-title">${c.name}</div><div class="meta">${c.description||""}</div><div class="actions">${b.join("")||'<span class="meta">No contact method available</span>'}</div></article>`}
function renderReport(){let c=deviceContacts();$("#content").innerHTML=`<div class="top-actions"><button class="action" id="importBtn">⇧ Import Contacts</button><button class="action danger" id="removeBtn">Remove</button></div><div class="subtabs">${["all","active","inactive"].map(x=>`<button class="subtab ${x==="all"?"active":""}" data-cstate="${x}">${x[0].toUpperCase()+x.slice(1)}</button>`).join("")}</div><div id="contactRows" class="stack"></div>`;renderContactRows(c,"all");$("#importBtn").onclick=()=>alert("Import contacts into this device only. GitHub does not store contacts.");$("#removeBtn").onclick=()=>{if(confirm("Remove all contacts stored on this device?")){localStorage.removeItem("local-alerts-contacts");renderReport()}};$("#content").querySelectorAll("[data-cstate]").forEach(b=>b.onclick=()=>{let state=b.dataset.cstate;$("#content").querySelectorAll("[data-cstate]").forEach(x=>x.classList.toggle("active",x===b));renderContactRows(deviceContacts(),state)})}
function renderContactRows(c,state){let list=state==="active"?c.filter(x=>x.active!==false):state==="inactive"?c.filter(x=>x.active===false):c;$("#contactRows").innerHTML=list.map(contactCard).join("")||'<div class="empty">No contacts stored on this device.</div>'}
function show(p){page=p;selected="all";$("#backBtn").hidden=p==="home";document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===p));if(p==="report"){$("#categoryStrip").innerHTML="";renderReport()}else{categoryStrip();renderAlerts()};$("#content").scrollTop=0}
document.querySelectorAll(".nav").forEach(n=>n.onclick=()=>show(n.dataset.page));$("#backBtn").onclick=()=>show("home");
async function locate(){let g=$("#gpsStatus");g.className="status gps-on";g.textContent="GPS: Getting…";if(!navigator.geolocation){g.className="status gps-off";g.textContent="GPS Off";return}navigator.geolocation.getCurrentPosition(async p=>{g.textContent="GPS On";let lat=p.coords.latitude,lon=p.coords.longitude;$("#location").textContent=`GPS ${lat.toFixed(6)}, ${lon.toFixed(6)} — finding address…`;try{let u=`https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${lat}&lon=${lon}&zoom=18&addressdetails=1`;let r=await fetch(u,{headers:{Accept:"application/json"}});if(!r.ok)throw Error();let d=await r.json();$("#location").textContent=(d.display_name||"Address unavailable")+" · GPS "+lat.toFixed(6)+", "+lon.toFixed(6)}catch{$("#location").textContent=`GPS ${lat.toFixed(6)}, ${lon.toFixed(6)} — address service unavailable`}},()=>{g.className="status gps-off";g.textContent="GPS Off";$("#location").textContent="GPS permission not granted"},{enableHighAccuracy:true,timeout:15000,maximumAge:0})}
async function checkData(){let d=$("#dataStatus");d.textContent="Data: Checking…";try{let r=await fetch("./data.js",{cache:"no-store"});if(!r.ok)throw Error();d.className="status data-on";d.textContent=navigator.onLine?"Data On":"Data Cached"}catch{d.className="status data-off";d.textContent="Data Off"}}
$("#locBtn").onclick=locate;$("#gpsStatus").onclick=locate;$("#dataStatus").onclick=checkData;window.addEventListener("online",checkData);window.addEventListener("offline",()=>{let d=$("#dataStatus");d.className="status data-off";d.textContent="Data Off"});if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));show("home");